# Generated by Django 3.2.9 on 2021-11-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('studentId', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('repeatPassword', models.TextField()),
                
            ],
        ),
    ]
