# Generated by Django 3.2.9 on 2021-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(default=' ', max_length=1000)),
                ('timeStamp', models.CharField(default=' ', max_length=1000)),
                ('leaveTimeStamp', models.CharField(default=' ', max_length=1000)),
            ],
        ),
    ]
