# Generated by Django 3.2.9 on 2021-12-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_date'),
        ('club_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubenrollment',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='clubenrollment',
            name='id',
        ),
        migrations.AddField(
            model_name='clubenrollment',
            name='club',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clubs.club'),
        ),
    ]
