# Generated by Django 3.2.9 on 2021-12-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_date'),
        ('club_enrollment', '0002_auto_20211222_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubenrollment',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clubs.club'),
        ),
    ]
