# Generated by Django 3.2.9 on 2021-12-23 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_enrollment', '0003_alter_clubenrollment_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubenrollment',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
