# Generated by Django 3.2.9 on 2021-12-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_enrollment', '0005_auto_20211223_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubenrollment',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubenrollment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
