# Generated by Django 3.2.9 on 2021-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(default='Awesome club', max_length=1000),
        ),
    ]
