# Generated by Django 3.2.9 on 2021-11-30 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
