# Generated by Django 3.2.9 on 2021-11-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteClubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.CharField(default='Awesome club', max_length=1000)),
                ('status', models.CharField(default='Awesome club', max_length=1000)),
                ('clubId', models.CharField(max_length=1000)),
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='createclubrequest',
            name='request',
        ),
        migrations.AddField(
            model_name='createclubrequest',
            name='status',
            field=models.CharField(default='Awesome club', max_length=1000),
        ),
        migrations.AddField(
            model_name='createclubrequest',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='createclubrequest',
            name='timeStamp',
            field=models.CharField(default='Awesome club', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
