# Generated by Django 3.2.9 on 2021-12-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20211214_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createclubrequest',
            old_name='student_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='deleteclubrequest',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
