# Generated by Django 3.2.9 on 2021-12-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_joinclubrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createclubrequest',
            old_name='clubDescription',
            new_name='club_description',
        ),
        migrations.RenameField(
            model_name='createclubrequest',
            old_name='clubName',
            new_name='club_name',
        ),
        migrations.RenameField(
            model_name='deleteclubrequest',
            old_name='clubId',
            new_name='club_id',
        ),
    ]
