# Generated by Django 3.2.9 on 2021-12-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20211220_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinclubrequest',
            old_name='clubId',
            new_name='club_id',
        ),
    ]
