# Generated by Django 3.2.9 on 2021-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_rename_clubid_joinclubrequest_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclubrequest',
            name='status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='createclubrequest',
            name='timeStamp',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='deleteclubrequest',
            name='status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='deleteclubrequest',
            name='timeStamp',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='joinclubrequest',
            name='status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='joinclubrequest',
            name='timeStamp',
            field=models.CharField(max_length=1000),
        ),
    ]
