# Generated by Django 3.2.9 on 2021-12-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_joinclubwithinforequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createclubrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='createclubrequest',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='deleteclubrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deleteclubrequest',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='joinclubrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='joinclubrequest',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='joinclubwithinforequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='joinclubwithinforequest',
            name='timeStamp',
        ),
    ]
