# Generated by Django 3.2.9 on 2021-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
