# Generated by Django 3.2.9 on 2021-11-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_club_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
