# Generated by Django 3.2.9 on 2021-11-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211119_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
